### ISSUE TITLE
Incorrect Clone Link

### ISSUE THREAD

**Issue by hassandraga** [Shad7ows/SpectrumIDEV2#4]
Right now this link on this repo is incorrect
`git clone https://github.com/alifcommunity/SpectrumIDEV2`

You should move `SpectrumIDEV2` to `alifcommunity`, Or change link to
h`ttps://github.com/Shad7ows/SpectrumIDEV2.git`

**Comment by Shad7ows** [comment]
تم نقل الى مخزن ألف

**Comment by Shad7ows** [comment]
> Good, Are you planning to remove https://github.com/alifcommunity/SpectrumIDE ?

نعم الافضل ترك محرر طيف النسخة الجديدة فقط ولا داعي للنسخة السابقة في مخزن مجتمع ألف

**Comment by Shad7ows** [comment]
اكتفيت بتغيير اسم النسخة الى SpectrumIDEV1
